USE ROLE ACCOUNTADMIN;
CREATE USER DBT_USER PASSWORD='your_password' DEFAULT_ROLE = SYSADMIN MUST_CHANGE_PASSWORD = false;
GRANT ROLE SYSADMIN TO USER DBT_USER;

CREATE DATABASE DEV;
CREATE SCHEMA "DEV"."JAFFLE_SHOP"; -- to use it for the jaffle-shop project from dbt-labs
GRANT ALL ON DATABASE "DEV" TO ROLE SYSADMIN;
